PL/SQL Developer Test script 3.0
10
begin
  -- Call the function
  :result := PACK_NOTAFISCAL.RETORNA_QUANTIDADEDECARROS(I_NR_ANOMODELO => :I_NR_ANOMODELO);
  
  IF PACK_NOTAFISCAL.RETORNA_QUANTIDADEDECARROS(:I_NR_ANOMODELO) > 0 THEN
    :DESCRICAO := 'TEM CARRO';
  ELSE
    :DESCRICAO := 'NAO TEM CARRO';
  END IF;   
end;
3
result
1
0
4
I_NR_ANOMODELO
1
2000
3
DESCRICAO
1
NAO TEM CARRO
5
2
V_COUNT
